import "./globals.css";
import { Inter } from "next/font/google";
import { headers, cookies } from 'next/headers'
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Space21 Management",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Space21 Management</title>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
